export enum StockMovementType {
  INITIAL = 'INITIAL',
  INCREMENT = 'INCREMENT',
  DECREMENT = 'DECREMENT',
  MINIMUM_CHANGE = 'MINIMUM_CHANGE',
  DEACTIVATION = 'DEACTIVATION',
  REACTIVATION = 'REACTIVATION',
}
