export enum SaleStatus { PROCESSING = 'PROCESANDO', CONFIRMED = 'CONFIRMADA', FAILED = 'FALLIDA', CANCELLED = 'ANULADA' }
export enum FiscalStatus { PENDING_EXTERNAL = 'PENDIENTE_CONTADOR', EXTERNAL_INVOICED = 'FACTURADA_EXTERNAMENTE' }
