export enum TaxCondition {
  NOT_DEFINED = 'NO_DEFINIDA',
  FINAL_CONSUMER = 'CONSUMIDOR_FINAL',
  REGISTERED_RESPONSIBLE = 'RESPONSABLE_INSCRIPTO',
  MONOTRIBUTE = 'MONOTRIBUTO',
  EXEMPT = 'EXENTO',
}
