export enum FinancialMovementKind {
  INCOME = 'INGRESO',
  EXPENSE = 'GASTO',
}

export enum FinancialMovementCategory {
  SALE = 'VENTA',
  CHECK = 'CHEQUE',
  REPLENISHMENT = 'REPOSICION_AUTOMATICA',
  PURCHASE = 'COMPRA_PRODUCTOS',
  ACCOUNT_PAYMENT = 'COBRO_CUENTA_CORRIENTE',
  SUPPLIER_ACCOUNT_PAYMENT = 'PAGO_CUENTA_PROVEEDOR',
  MANUAL = 'GASTO_MANUAL',
}

export enum FinancialPaymentMethod {
  CASH = 'EFECTIVO',
  TRANSFER = 'TRANSFERENCIA',
  CREDIT = 'CREDITO',
  CHECK = 'CHEQUE',
  HISTORICAL = 'PAGADO_ANTES_SISTEMA',
}
